# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: vsce_publish

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  publish-vsce:
    name: "vsce-publish"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && github.head_ref == 'package/vitawind' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}